version: '3.4'
services:
  #person-microservice
  person:
    build:
      dockerfile: ./watcher.Dockerfile
    volumes:
      - ./src/person-microservice/:/src/
      - ./conf/person/appsettings.json:/src/Conduit.Person.WebApi/appsettings.json
      - ./conf/person/appsettings.Development.json:/src/Conduit.Person.WebApi/appsettings.Development.json
    depends_on:
      - person-storage
    ports:
      - "3050:80"
    env_file:
      - ./conf/person/dev.env

  #person-storage
  # neo4j:my_password
  person-storage:
    ports: 
      - "3051:7474"
      - "3052:7687"
    volumes:
      - ./volumes/person-storage/neo4j/data/:/data/
      - ./volumes/person-storage/neo4j/logs/:/logs/
    env_file:
      - ./conf/person-storage/dev.env
        
  #auth-microservice
  auth:
    build:
      dockerfile: ./watcher.Dockerfile
    volumes:
      - ./src/auth-microservice/:/src/
      - ./conf/auth/appsettings.json:/src/Conduit.Auth.WebApi/appsettings.json
      - ./conf/auth/appsettings.Development.json:/src/Conduit.Auth.WebApi/appsettings.Development.json
    depends_on:
      - auth-storage
    ports:
      - "3060:80"
    env_file:
      - ./conf/person/dev.env

  #auth-storage
  # postgres
  # login postgres:my_password
  auth-storage:
    ports:
      - "3061:5432"
    env_file:
      - ./conf/auth-storage/dev.env
    volumes:
      - ./volumes/auth-storage/postgres/data/:/var/lib/postgresql/data/pgdata/
      - ./volumes/auth-storage/postgres/logs/:/pg_log/
    command: postgres -c logging_collector=on -c log_directory=/pg_log -c log_statement=all -c log_rotation_age=5

  #proxy
  # nginx
  proxy:
    volumes:
      - ./conf/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - person
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'

  #queue
  # rabbitmq
  # login myUser:myPassword
#  queue: 
#    hostname: "queue"
#    labels:
#      NAME: "queue"
#    volumes:
#      - ./conf/queue/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#    ports:
#      - "5671:5671" # Queue
#      - "15671:15671" # UI
