version: '3.4'
services:
  #person-microservice
  articles:
    image: ${DOCKER_REGISTRY-}articles:prebuild
    build:
      context: ./src/articles-microservice/
  
  articles-storage:
    image: postgres:latest
  
  #person-microservice
  person:
    image: ${DOCKER_REGISTRY-}person:prebuild
    build:
      context: ./src/person-microservice/

  person-storage:
    image: neo4j:latest

  #auth-microservice
  auth:
    image: ${DOCKER_REGISTRY-}auth:prebuild
    build:
      context: ./src/auth-microservice/

  auth-storage:
    image: mongo:latest

  #likes-microservice
  likes:
    image: ${DOCKER_REGISTRY-}likes:prebuild
    build:
      context: ./src/likes-microservice/

  likes-storage:
    image: redis:7.0-rc
  
  #comments-microservice
  comments:
    image: ${DOCKER_REGISTRY-}comments:prebuild
    build:
      context: ./src/comments-microservice/

  comments-storage:
    image: postgres:latest

  #image-microservice
  image:
    image: ${DOCKER_REGISTRY-}image:prebuild
    build:
      context: ./src/image-microservice/

  image-storage:
    image: postgres:latest

  #proxy
  proxy:
    image: nginx:alpine
  #
  #  #queue
  queue:
    image: rabbitmq:management
